export const storeProduct = [
	{
		_id: 11,
		count: 1,
		product: "Bell Pepper",
		image: "./image/bell pepper.jpg",
		price: 750,
	},
	{
		_id: 12,
		count: 1,
		product: "Chilli Pepper",
		image: "./image/chilli pepper.jpg",
		price: 655,
	},
	{
		_id: 13,
		count: 1,
		product: "Dry Pepper",
		image: "./image/dry pepper.jpg",
		price: 400,
	},
	{
		_id: 14,
		count: 1,
		product: "Green Pepper",
		image: "./image/green pepper.jpg",
		price: 750,
	},
	{
		_id: 15,
		count: 1,
		product: "Onions",
		image: "./image/onions.jpg",
		price: 1000,
	},
	{
		_id: 16,
		count: 1,
		product: "irish potato",
		image: "./image/irish potato.jpg",
		price: 800,
	},
	{
		_id: 17,
		count: 1,
		product: "Red Pepper",
		image: "./image/red pepper.jpg",
		price: 620,
	},
	{
		_id: 18,
		count: 1,
		product: "tomato",
		image: "./image/tomato.jpg",
		price: 1515,
	},
	{
		_id: 19,
		count: 1,
		product: "yellow bellpepper",
		image: "./image/yellow bellpepper.jpg",
		price: 1230,
	},
]